spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=false
    username: root
    password: p@ssword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8
  url: jdbc:mysql://localhost:3306
  schemas: blog
  user: root
  password: p@ssword
  baseline-on-migrate: true


logging:
  level:
    root: info
    com.blog: debug
file:
    path: log/blog-dev.log





